問２
participant "SceneManager"
participant "TitleScene"
participant "Library"
participant "TitleBackGround"
participant "TitleName"
participant "TitleSelectManager"
participant "TitleTimeManager"

loop true

opt TitleSceneになったら
activate SceneManager

create TitleScene
SceneManager -> TitleScene:new
activate TitleScene

== コンストラクタ ==
create Library
TitleScene->Library:new
activate Library

create TitleBackGround
TitleScene->TitleBackGround:new
activate TitleBackGround

create TitleName
TitleScene->TitleName:new
activate TitleName

create TitleSelectManager
TitleScene->TitleSelectManager:new
activate TitleSelectManager

create TitleTimeManager
TitleScene->TitleTimeManager:new
activate TitleTimeManager

end

SceneManager -> TitleScene:Control()
TitleScene -> TitleSelectManager: SelectManager:Control()

alt シーンが変わっていない
TitleSelectManager-->TitleScene:TitleScene
TitleScene-->SceneManager:TitleSceneで戻ってきたそのままのシーン

else シーンが変わった
TitleSelectManager-->TitleScene:変わった先のシーン
TitleScene-->SceneManager:TitleSceneで戻ってきた変わった先のシーン
SceneManager->TitleScene:delete

== デストラクタ ==
TitleScene->Library:Release
TitleScene->TitleBackGround:delete
deactivate TitleBackGround
destroy TitleBackGround
TitleScene->TitleName:delete
deactivate TitleName
destroy TitleName
TitleScene->TitleSelectManager:delete
deactivate TitleSelectManager
destroy TitleSelectManager
TitleScene->TitleTimeManager:delete
deactivate TitleTimeManager
destroy TitleTimeManager
destroy TitleScene

end
end
