@startuml
participant SceneManager
participant TitleScene
participant TitleBackGround
participant TitleSelectManager
participant TitleTimeManager
participant TitleName

/' ------------------ loop ------------------------------- '/
loop メインループ


[-> SceneManager
activate SceneManager

 /' ----------------------- alt ----------------------------- '/
alt TitleSceneに切り替わったか

create TitleScene
SceneManager -> TitleScene
activate TitleScene

end
 /' ---------------------- alt end --------------------------- '/


 
== コンストラクタ ==

create TitleBackGround
TitleScene -> TitleBackGround : new
create TitleSelectManager
TitleScene -> TitleSelectManager : new
create TitleTimeManager
TitleScene -> TitleTimeManager : new
create TitleName
TitleScene -> TitleName : new




ref over TitleScene, TitleName : 別シーケンスを参照


 /' ---------------------- alt -------------------------- '/
alt TitleScene以外に切り替わったか

SceneManager -> TitleScene

end
 /' ---------------------- alt end --------------------------- '/


== デストラクタ ==


TitleScene -> TitleBackGround : delete
destroy TitleBackGround
TitleScene -> TitleSelectManager : delete
destroy TitleSelectManager
TitleScene -> TitleTimeManager : delete
destroy TitleTimeManager
TitleScene -> TitleName : delete
destroy TitleName
destroy TitleScene


[<- SceneManager
deactivate SceneManager

end
 /' --------------------- loop end ---------------------------- '/
@enduml
