@startuml

class Library
{
+m_hWnd : HWND
+m_pD3DManager : D3DManager*
+m_pDSoundManager : DSoundManager*
+m_pXInput : XInput*
+m_pTexture : Texture*
+m_pVertex : Vertex*
+m_pUVSetter : UVSetter*
}

abstract class Scene
{
+Scene()
+ {abstract} Control() : virtual SCENE_NUM
+ {abstract} Draw() : virtual void 
+ {abstract} PadCheck() : virtual void
+m_PadState[PAD_MAX] : bool
+m_PadOldState[PAD_MAX] : bool
}

class SceneManager
{
+SceneManager(Library* pLibrary)
+Control() : bool
+Draw() : void
+m_pScene : Scene*
}

class TitleBackGround
{
+TitleBackGround(Library* pLibrary, LPDIRECT3DTEXTURE9 pTexture)
+Control() : void
+Draw() : void
}

class TitleName
{
+TitleName(Library* pLibrary, LPDIRECT3DTEXTURE9 pTexture);
+Control() : void
+Draw() void
}

class TitleScene
{
+TitleScene(Library* pLibrary)
+Control() : virtual SCENE_NUM
+Draw() : virtual void
+PadCheck() virtual void
}

class TitleSelectManager
{
+TitleSelectManager(Library* pLibrary, LPDIRECT3DTEXTURE9 pTexture, bool*pPadState, bool* pPadOldState)
+Control() : TITLESELECT_ID
+Draw() : void
}

class TitleTimeManager
{
+TitleTimeManager(Library* pLibrary, LPDIRECT3DTEXTURE9 pTexture)
+Control() : bool
+Draw() : void
}

Scene              --o  SceneManager
Library            --o  TitleSelectManager
Library            --o  TitleScene
Library            --o  TitleName
Library            --o  SceneManager
Library            --o  TitleBackGround
Library            --o  TitleTimeManager
TitleBackGround    --*  TitleScene
TitleSelectManager --*  TitleScene
TitleName          --*  TitleScene
TitleTimeManager   --*  TitleScene
TitleScene         --|> Scene

@enduml
